### PR TITLE
Replace deprecated String.prototype.substr()

### PR DESCRIPTION
**Pull request by CommanderRoot**
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]

**Comment by CarlSchwan** [comment]
Thanks :)

**Comment by CommanderRoot** [comment]
Did the revert fix the issue? I have re-checked the code in this PR and the only thing I could find which could result in a different output with `.slice()` instead of `.substr()` was on this line https://github.com/nextcloud/logreader/commit/319c08e06c20626f3fe5a9aaeed76483822c9f72#diff-a399f4f7618b3592834a1e57a93657c1618c0df173b27e903e5493a63e0a0853R37 if endPos is -1.
So replacing it with
```
const message = json.slice(startPos, endPos !== -1 ? endPos : 0);
```
would fix that as well.

**Comment by nickvergessen** [comment]
The backport is still pending https://github.com/nextcloud/logreader/pull/704

**Pull request merged**
