### PR TITLE
feat: Allow pasting log entries

### PR DESCRIPTION
**Pull request by susnux**
Before the Vue migration there was a hidden feature allowing you to paste on the logreader to show your clipboard content (log entries).
This is quite useful when e.g. having logs from GitHub issues.

So this PR brings back that function, to make it a bit more discoverable I added a info note to the settings modal:

image

And pasting looks like this, Firefox does not support Clipboard API so a fallback prompt is used:

https://github.com/nextcloud/logreader/assets/1855448/1601ad0c-e913-42b8-b9bd-948b21650638

Chromium / Chrome supports it, it just asks for confirmation / permissions and looks like this:

https://github.com/nextcloud/logreader/assets/1855448/6f5e289c-cfac-4242-9116-df8cdba95ae8

### CODE REVIEW

**Comment by szaimen** [comment]
Just tested and seems like I found two bugs?
image
image

**Comment by susnux** [comment]
@szaimen what do you mean with bugs? Or better: What did you do to end up with that state?

**Comment by szaimen** [comment]
> @szaimen what do you mean with bugs? Or better: What did you do to end up with that state?

I ended up in this state when I was testing the PR with my easy test instance which logs the log to stdout by default. If you now upload a log file or paste from clipboard, you can see the screenshots.

**Comment by icewind1991** [comment]
instead of using keyboard events, you can use the [`paste`](https://developer.mozilla.org/en-US/docs/Web/API/Element/paste_event) event which will give you the text on all (afaik) browsers.

**Comment by icewind1991** [comment]
switched to the `paste` event

**Review by icewind1991 — APPROVED** [review]

**Pull request merged**
