### PR TITLE
Some small fixes for NC 21

### PR DESCRIPTION
**Pull request by yamanq**
I noticed a couple small errors so I fixed them.

1. Commands must return int values: https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/upgrade-guide.html#symfony-update
2. Using the Watch command with an empty log file results in an error due to null last log item.

### CODE REVIEW

**Review by icewind1991 — APPROVED** [review]
Thanks!

**Comment by icewind1991** [comment]
I'll look into failing CI and fix things

**Comment by yamanq** [comment]
I fixed another issue where occ log:tail creates several errors due to the 'args' key being missing from some items in the trace. I also corrected my issues with the CI and rebased. Is there anything else I need to change?

**Comment by yamanq** [comment]
Do I need to do anything else to get this merged? Thanks!

**Comment by icewind1991** [comment]
Sorry for the delays

**Pull request merged**
