### PR TITLE
Fetch new log messages using AJAX fixes #19

### LINKED ISSUE #19: [Feature] Get new logs with ajax
Would it be possible to get new log's with ajax? Would be very handy during development of an app.

### PR DESCRIPTION
**Pull request by LEDfan**

### CODE REVIEW

**Comment by LEDfan** [comment]
cc @brantje @mightyBroccoli

**Comment by brantje** [comment]
Awesome! Code looks good

**Comment by mightyBroccoli** [comment]
This is awesome. I will patch my logreader later today to test the functionality.

**Comment by LEDfan** [comment]
I just added a fadeout highlight to the new loaded messages:
peek 2017-07-09 16-25

**Comment by icewind1991** [comment]
Great work 👍 

Cleaned up the code a bit and added a toggle to control live updating

**Comment by LEDfan** [comment]
Nice! For me this can be merged :smile:

**Pull request merged**
