### PR TITLE
[26] allow printing log messages during occ

### PR DESCRIPTION
**Pull request by icewind1991**
Backport of https://github.com/nextcloud/logreader/pull/873

- [x] requires https://github.com/nextcloud/server/pull/38815

### CODE REVIEW

**Review by blizzz — CHANGES_REQUESTED** [review]
`BeforeMessageLoggedEvent` was introduced in 27.0.1 only

(that's what the require is about, just blocking to avoid accidental merge)

**Comment by blizzz** [comment]
CI is failing

```
ERROR: InvalidArgument - lib/Listener/LogListener.php:58:62 - Argument 3 of OCA\LogReader\Log\Console::log expects array<array-key, mixed>, but string provided (see https://psalm.dev/004)
			$this->console->log($event->getLevel(), $event->getApp(), $event->getMessage());
```

I would have expected this on the master and 27 PRs as well, but there it didn't appear.

**Comment by susnux** [comment]
@blizz on master & stable27 the typing of `BeforeMessageLoggedEvent` is correct, but for stable26 the typing of `getMessage()` is string instead of array.

**Comment by susnux** [comment]
Backport here: https://github.com/nextcloud/server/pull/41357/files

**Comment by blizz** [comment]
@blizzz
    On Thursday, November 9, 2023, 03:49:24 AM MST, Ferdinand Thiessen ***@***.***> wrote:  
 
 


@blizz on master & stable27 the typing of BeforeMessageLoggedEvent is correct, but for stable26 the typing of getMessage() is string instead of array.

**Comment by susnux** [comment]
@blizz sorry for the ping

**Review by blizzz — APPROVED** [review]

**Pull request merged**
