### PR TITLE
Audit and update dependencies [stable25]

### PR DESCRIPTION
**Pull request by Antreesy**
Update dependencies with `audit fix` based on security report before upcoming release
Smoke tested on web client

### CODE REVIEW

**Review by icewind1991 — APPROVED** [review]

**Comment by Antreesy** [comment]
@icewind1991 everything except php7.4 tests for master branch are green. Could we force merge it?

**Comment by susnux** [comment]
> @icewind1991 everything except php7.4 tests for master branch are green. Could we force merge it?

should be fixed with: https://github.com/nextcloud/logreader/pull/886

**Comment by susnux** [comment]
Rebased

**Comment by susnux** [comment]
That CI was already  green, failure unrelated.

**Pull request merged**
