### PR TITLE
fixed typo "cased by" -> "caused by"

### PR DESCRIPTION
**Pull request by joernhees**
not entirely sure about the build dir stuff, i simply replaced this in all project and also fixed the weird german translation it caused. Other translations probably are wrong too.

### CODE REVIEW

**Comment by rakekniven** [comment]
Translations are done at Transifex. Not sure if so many files needed to be touched.

**Comment by joernhees** [comment]
If you see a simpler / more elegant / better way of fixing it, please take it from here.

Thing is that by the typo in the key all auto translations are wonky.

**Comment by rakekniven** [comment]
IMHO the only file which need to be changed is:

js/Components/Exception.js

All others will be changed at Transifex as soon as the Translators will think about the change and adapt the strings.

**Comment by icewind1991** [comment]
Fixed with 5ebe9c227541cde6b00652e5d91abf27f6b78885

**Pull request closed without merging**
