### PR TITLE
chore: Migrate to `@nextcloud/vite-config`

### PR DESCRIPTION
**Pull request by susnux**

### CODE REVIEW

**Comment by skjnldsv** [comment]
node still failing :thinking:

**Comment by skjnldsv** [comment]
Something must be dynamically integrated in the final bundle, it keeps changing. A date or something maybe? A random hash ?

**Comment by susnux** [comment]
This still uses the beta17 release (way too much beta versions), which is just the renamed package. beta18 fixed the non deterministic license information (which included a build date and flaky dependencies).

**Pull request merged**
