### PR TITLE
change context to get strings to Transifex

### PR DESCRIPTION
**Pull request by rakekniven**
Reported at Transifex.

Signed-off-by: rakekniven <2069590+rakekniven@users.noreply.github.com>

### CODE REVIEW

**Review by Valdnet — APPROVED** [review]

**Comment by rakekniven** [comment]
Adapted it. See #551 

Now wait until tomorrow morning and check TX.

**Comment by Valdnet** [comment]
@rakekniven This still needs to be changed. Can you?
https://github.com/nextcloud/logreader/blob/5cbc4876f9f60d10604c5c36ee032f683b410678/js/Components/Settings.js#L21

**Comment by Valdnet** [comment]
@rakekniven Before merging, you should build:

>  build/main.js
> build/main.js.map

**Comment by rakekniven** [comment]
> @rakekniven Before merging, you should build:
> 
> > build/main.js
> > build/main.js.map

Why? The packed js files are not important for Transifex. They are ignored by `.l10nignore` file.
I thought this is important for release or testing.

**Comment by Valdnet** [comment]
> Why? The packed js files are not important for Transifex.

I know 😉. Build is a certain test whether the final release will be built correctly. In this case, the changes were small for the entire code. The compilation might have been skipped.

**Pull request merged**
